import type { CustomerApplicationListRow } from "./types";

/**
 * Illustrative rows for the admin list when there's no asgard_admin session
 * or Supabase env vars are missing. Match the shape returned by
 * listCustomerApplications().
 */
export const PREVIEW_CUSTOMER_APPLICATIONS: CustomerApplicationListRow[] = [
  {
    id: "ca-prev-1",
    status: "submitted",
    legal_name: "Helios Aerodyne, Inc.",
    dba: "Helios",
    hq_state: "CA",
    hq_country: "US",
    org_type: "startup",
    derived_tier: "defense_prime",
    itar: true,
    defense_program: true,
    intake_email: "jordan@heliosaerodyne.com",
    submitted_at: "2026-04-25T16:42:00Z",
    reviewed_at: null,
    created_at: "2026-04-25T16:30:00Z",
  },
  {
    id: "ca-prev-2",
    status: "under_review",
    legal_name: "Northstar Propulsion Systems, LLC",
    dba: null,
    hq_state: "WA",
    hq_country: "US",
    org_type: "oem",
    derived_tier: "enterprise",
    itar: true,
    defense_program: false,
    intake_email: "ops@northstarprop.com",
    submitted_at: "2026-04-22T11:08:00Z",
    reviewed_at: "2026-04-23T09:14:00Z",
    created_at: "2026-04-22T11:00:00Z",
  },
  {
    id: "ca-prev-3",
    status: "approved",
    legal_name: "Pelican Microsat Co.",
    dba: "Pelican",
    hq_state: "CO",
    hq_country: "US",
    org_type: "startup",
    derived_tier: "growth_stage",
    itar: false,
    defense_program: false,
    intake_email: "alex@pelican.space",
    submitted_at: "2026-04-18T09:55:00Z",
    reviewed_at: "2026-04-21T14:02:00Z",
    created_at: "2026-04-18T09:50:00Z",
  },
  {
    id: "ca-prev-4",
    status: "revisions_requested",
    legal_name: "Coastal Avionics Group",
    dba: null,
    hq_state: "FL",
    hq_country: "US",
    org_type: "prime",
    derived_tier: "itar_controlled",
    itar: true,
    defense_program: false,
    intake_email: "procurement@coastalavionics.io",
    submitted_at: "2026-04-12T14:18:00Z",
    reviewed_at: "2026-04-14T10:05:00Z",
    created_at: "2026-04-12T14:10:00Z",
  },
  {
    id: "ca-prev-5",
    status: "rejected",
    legal_name: "Briar Robotics",
    dba: null,
    hq_state: "MI",
    hq_country: "US",
    org_type: "startup",
    derived_tier: "growth_stage",
    itar: false,
    defense_program: false,
    intake_email: "founder@briar.bot",
    submitted_at: "2026-04-09T17:33:00Z",
    reviewed_at: "2026-04-10T08:21:00Z",
    created_at: "2026-04-09T17:30:00Z",
  },
];
