import type { SupplierApplicationListRow } from "./types";

/**
 * Illustrative supplier-application rows for the admin list when there's
 * no asgard_admin session or Supabase env vars are missing.
 */
export const PREVIEW_SUPPLIER_APPLICATIONS: SupplierApplicationListRow[] = [
  {
    id: "sa-prev-1",
    status: "submitted",
    legal_name: "Anvil Precision Machining, Inc.",
    dba: "Anvil",
    hq_state: "WA",
    hq_country: "US",
    itar_registered: true,
    cmmc_level: "level_2",
    primary_processes: ["CNC machining", "EDM", "Heat treat"],
    intake_email: "ops@anvilprecision.com",
    submitted_at: "2026-04-25T15:18:00Z",
    reviewed_at: null,
    created_at: "2026-04-25T15:00:00Z",
  },
  {
    id: "sa-prev-2",
    status: "under_review",
    legal_name: "Cardinal Composites Co.",
    dba: null,
    hq_state: "TX",
    hq_country: "US",
    itar_registered: false,
    cmmc_level: "none",
    primary_processes: ["Composites", "Assembly"],
    intake_email: "rfq@cardinalcomposites.com",
    submitted_at: "2026-04-22T10:42:00Z",
    reviewed_at: "2026-04-23T08:11:00Z",
    created_at: "2026-04-22T10:30:00Z",
  },
  {
    id: "sa-prev-3",
    status: "approved",
    legal_name: "Meridian Sheet Metal, LLC",
    dba: "Meridian",
    hq_state: "CA",
    hq_country: "US",
    itar_registered: true,
    cmmc_level: "level_1",
    primary_processes: ["Sheet metal", "Welding", "Coatings"],
    intake_email: "info@meridiansheet.com",
    submitted_at: "2026-04-18T09:14:00Z",
    reviewed_at: "2026-04-21T13:55:00Z",
    created_at: "2026-04-18T09:00:00Z",
  },
  {
    id: "sa-prev-4",
    status: "revisions_requested",
    legal_name: "Polaris Additive",
    dba: null,
    hq_state: "MN",
    hq_country: "US",
    itar_registered: false,
    cmmc_level: "none",
    primary_processes: ["Additive manufacturing"],
    intake_email: "founder@polarisadditive.com",
    submitted_at: "2026-04-12T16:08:00Z",
    reviewed_at: "2026-04-14T11:21:00Z",
    created_at: "2026-04-12T16:00:00Z",
  },
  {
    id: "sa-prev-5",
    status: "rejected",
    legal_name: "Borealis Tooling",
    dba: null,
    hq_state: "OR",
    hq_country: "US",
    itar_registered: false,
    cmmc_level: "none",
    primary_processes: ["CNC machining"],
    intake_email: "sales@borealistooling.io",
    submitted_at: "2026-04-09T12:33:00Z",
    reviewed_at: "2026-04-10T07:50:00Z",
    created_at: "2026-04-09T12:30:00Z",
  },
];
